### ISSUE TITLE
Add atom-linter integration

### ISSUE THREAD

**Issue by wooorm** [wooorm/mdast-lint#16]
Not a fan of coffee-script, but I’d dig in :wink:.

**Comment by zcei** [comment]
Would do the same for Sublime Text then, couldn't force myself to Atom so far :p

**Comment by wooorm** [comment]
Hmm that'd be awesome, but I have no idea how to create those!

**Comment by leipert** [comment]
et voilà: https://atom.io/packages/linter-markdown

**Comment by wooorm** [comment]
Very nice work! I guess that fixes things 😄. I’ll add a note on the README.
