### ISSUE TITLE
Ignore maximum-line-length on definitions

### ISSUE THREAD

**Issue by leipert** [wooorm/mdast-lint#21]
<img width="887" alt="screen shot 2015-08-05 at 09 28 54" src="https://cloud.githubusercontent.com/assets/2906107/9081004/1b08c618-3b59-11e5-9c78-d8bae2b121fa.png">

````markdown
[issue-46]: https://github.com/Galadirith/markdown-preview-plus/issues/46#issuecomment-124324926
[pandoc-cit]: http://pandoc.org/README.html#citations
````

**Comment by wooorm** [comment]
Working on it
