### ISSUE TITLE
Prevent markdown contents from being output before the warnings

### ISSUE THREAD

**Issue by alefteris** [wooorm/mdast-lint#23]
Unless I'm missing something, when I run `mdast -u mdast-lint README.md` I get in the output the complete markdown document contents before any warnings are printed. What I would like to do is just print any warnings. If there are no errors, I would like to get nothing at all or just a line stating that no warnings are found. Is this possible currently?

Thanks

**Comment by wooorm** [comment]
How about `mdast -u mdast-lint README.md 1> /dev/null`? That should do exactly what you want.

**Comment by wooorm** [comment]
You should be able to hide output by using the new `--no-stdout` option, as in: `mdast -u mdast-lint README.md --no-stdout`.

**Comment by alefteris** [comment]
The new option works as expected. Thanks a lot!
