### ISSUE TITLE
Return an error status when there are lint errors

### ISSUE THREAD

**Issue by alefteris** [wooorm/mdast-lint#24]
I would like to use the linter with a CI like TravisCI, so that when there are lint errors, it returns an error and the build fails. So I have in my package.json a script entry like `"lint": "mdast -u mdast-lint README.md"` and then I run `npm run lint`. Is that currently possible? I think currently it doesn't return an error, unless I'm missing something..

Thanks

**Comment by wooorm** [comment]
Not yet no. I'll get this working later today.

**Comment by wooorm** [comment]
You should be able to exit with `1` when using the new `--frail` option, as in: `mdast -u mdast-lint README.md --frail`

**Comment by alefteris** [comment]
Thanks for the new option. Works as expected. Thanks!
