### ISSUE TITLE
Reason missing in output

### ISSUE THREAD

**Issue by timkurvers** [wooorm/mdast-lint#26]
It seems the reasons are missing in the generated CLI output:

![screen shot 2015-10-19 at 21 43 07](https://cloud.githubusercontent.com/assets/378235/10589271/8304a3b8-76aa-11e5-8996-b676e44ea767.png)

Is there a flag to show these?

**Comment by wooorm** [comment]
Thanks for reporting, when I release the aforementioned commit, throwing away dependencies and re-installing should fix this :smile:

**Comment by timkurvers** [comment]
Thanks for the swift fix! :+1:
