### ISSUE TITLE
hard line breaks on paragraph nodes

### ISSUE THREAD

**Issue by datapimp** [wooorm/mdast-lint#27]
One thing that annoys me is my text editor sometimes inserts hard breaks in my paragraphs.  

Is there an easy way to automatically get rid of the hard line breaks for paragraphs with this tool?

**Comment by wooorm** [comment]
As in, a tool that replaces a newline (with surrounding white-space probably) with a space?

Or a rule that lints whether or not newlines are used?

**Comment by datapimp** [comment]
So if you take this file as an example

https://github.com/architects/brief-node/edit/master/test/example/docs/epics/model-definition-dsl.md

You'll see that the paragraphs are formatted nicely for the editor and easy to navigate in vim, line by line.

However, displaying this code in, for example, a pre tag, is ugly.  It is nicer when there is not hard line breaks.

The mdast-squeeze-paragraphs plugin makes the rendered output the same either way, which is nice.

What I would love is a way to automatically persist the paragraphs without the hard line breaks when I end up committing to version control.  

Prior to editing, I can easily break them up into lines again.

It seems like this tool could easily accomplish this.

**Comment by wooorm** [comment]
I see. We'll, mdast-lint just checks for stuff : without changing anything, so this should be a feature request

**Comment by datapimp** [comment]
oh. the README says that it can fix issues automatically.  I can try taking a crack at this

**Comment by wooorm** [comment]
Sorry about that, but to be fair, under the heading “Using mdast to fix your markdown”, it just mentions mdast and not mdast-lint.

If you have a better alternative to get the point across that that’s about **mdast** and *not* **mdast-lint**, please let me know :)

**Comment by datapimp** [comment]
I would probably just remove it then if there's no relation between the
ability to automatically fix markdown and this library.

I think it is doable though through the API I will let you know if i can
make it work

>

**Comment by wooorm** [comment]
@datapimp it’s in the docs because a lot of the things mdast-lint highlights can be fixed by using `mdast -o`, something which I though would help newcomers to mdast (through mdast-lint) get up to speed!

**Comment by datapimp** [comment]
Am i incorrect in thinking that there is a way to go from the ast to markdown as well as the usual markdown -> ast -> rendered (or stringified) output? I thought I remember seeing that somewhere.  To be fair you have about a hundred plugins all with a lot of documentation so it can blur together

**Comment by wooorm** [comment]
Yup: <https://github.com/wooorm/mdast/blob/master/doc/mdast.3.md#mdaststringifynode-file-options>
