### ISSUE TITLE
coala Integration

### ISSUE THREAD

**Issue by sils1297** [wooorm/mdast-lint#30]
You state you'd be interested in further integration. I'm the founder of a little open source project that aims to provide user interaction for any code analysis. Currently we're writing wrappers for linters like yours and the cool thing is integrating a linter can take as short as five minutes (given that you know coala a bit.)

An example for an integration with indent (which actually generates results that allow coala to also fix the issues automatically if so desired by the user) is here: https://github.com/coala-analyzer/coala/commit/58ecf967b61c11235d30909ae1f6dcab00ef0895#diff-4303149460ecafb6e4092292d03d667aR13

Would you be interested in writing mdast-lint integration for coala? That would provide you with a plugin to:

- gedit
- sublime
- atom

(Though we haven't uploaded those anywhere yet but they're there.)

It also gives you a nice user interaction and features like JSON export and stuff like that, in case you miss those.

**Comment by wooorm** [comment]
Indeed, I’d love for more integrations to be developed. However, I don’t have the time. Although coala seems great, I cannot put in the time and effort to work on this. Sorry.

What I can offer is time guiding someone else, such as you, in getting that ecosystem integrated with **mdast-lint**. Ping me if interested.

P.S., See [linter-markdown](https://github.com/AtomLinter/linter-markdown) for an example integration with mdast-lint, and [`doc/api`](https://github.com/wooorm/mdast-lint/blob/master/doc/api.md) for the programming interface of mdast-lint.

**Comment by sils1297** [comment]
@wooorm thanks, will contact you in private about this, thanks!

**Comment by wooorm** [comment]
Okay!
